# Courtesy of https://github.com/Expugn/priconne-database
# This workflow will auto download a database and push any changes if found

name: update

on:
  # run this task every minute 45 of every hr of every day
  # preload usually happens at minute 45? but actions fires 5mins later
  # schedule:
  # - cron: '45 * * * *'

  # allow this task to be run manually from Actions tab
  workflow_dispatch:

jobs:
  # needs access to {{ secrets.DEPLOY_ACCESS_TOKEN }} with at least public_repo scope
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python [3.x]
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Check Update
        id: check_for_update
        run: python download.py

      # btw for some reason installing UnityPack here causes issues
      # it's kind of a pain to debug sooooo UnityPack is provided in vendor/UnityPack

      - name: Install Python dependencies
        if: ${{ steps.check_for_updates.outputs.success == 'true' }}
        run: |
          pip install requests
          pip install lz4
          pip install UnityPy
          pip install brotli

      - name: Run download.py
        if: ${{ steps.check_for_updates.outputs.success == 'true' }}
        id: download_database
        run: python download.py

      # assuming there are new changes
      - name: Update files on Git
        if: ${{ steps.check_for_updates.outputs.success == 'true' }}
        run: |
          git config --global user.name "MightyZanark"
          git config --global user.email "40352213+MightyZanark@users.noreply.github.com"
          git add ./redive_en.db
          git add ./redive_en.db.br
          git add ./last_version_en.json
          git commit -m "[Automated] Database Update - ${{ steps.download_database.outputs.title }}" -m '
          ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          This is an automated process. Issues may or may not have occured.
          ${{ steps.download_database.outputs.diff }}'
          git push
        env:
          github_token: ${{ secrets.DEPLOY_ACCESS_TOKEN }}
          repository: ${{ github.repository }}
